In [1]:
import pandas as pd
df= pd.read_csv(r"C:\Users\Karan Mayank\Downloads\customer_shopping_behavior.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [10]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [14]:
df['age'].describe()

count    3900.000000
mean       44.068462
std        15.207589
min        18.000000
25%        31.000000
50%        44.000000
75%        57.000000
max        70.000000
Name: age, dtype: float64

In [31]:
bins = [0, 25, 40, 55, 100]
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [32]:
df[df['age'] == 18][['age', 'age_group']]

      age    age_group
24     18  Young Adult
25     18  Young Adult
72     18  Young Adult
228    18  Young Adult
357    18  Young Adult
...   ...          ...
3610   18  Young Adult
3714   18  Young Adult
3725   18  Young Adult
3806   18  Young Adult
3868   18  Young Adult

[69 rows x 2 columns]

In [33]:
df[['age','age_group']].head(100)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
..  ...          ...
95   37        Adult
96   32        Adult
97   21  Young Adult
98   20  Young Adult
99   26        Adult

[100 rows x 2 columns]

In [18]:
df[df['age'] == 18]['age_group'].value_counts(dropna=False)

age_group
Adult          69
Young           0
Early Adult     0
Adult Plus      0
Mid Senior      0
Senior          0
Name: count, dtype: int64

In [19]:
df['age'].min()

18

In [20]:
## create column purchase_frequency_days

frequency_mapping= {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'every 3 months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping).astype('Int64')

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

In [22]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [23]:
df['discount_applied'].value_counts()

discount_applied
No     2223
Yes    1677
Name: count, dtype: int64

In [24]:
df=df.drop('promo_code_used',axis=1)

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [26]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\karan mayank\anaconda3\lib\site-packages (9.5.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\karan mayank\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\karan mayank\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\karan mayank\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\karan mayank\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [28]:
from sqlalchemy import create_engine
host = "localhost"
port = "3306"
username = "root"
password = "karansingh100"
database = "customer_behaviour_analytics"
engine = create_engine("mysql+pymysql://root:karansingh100@localhost:3306/customer_behaviour_analytics")
table_name="customer"    ##table name 
df.to_sql(table_name,con=engine,if_exists="replace",index=False)

engine.connect()
print("CONNECTED")

CONNECTED

In [29]:
from sqlalchemy import create_engine

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

engine.connect()
print("✅ Python successfully connected to MySQL")

✅ Python successfully connected to MySQL

In [34]:
df.to_sql(
    'customer_clean',
    engine,
    if_exists='replace',
    index=False
)

3900